### PR TITLE
chore(dependencies): update dependencies and use new subscriptions API

### PR DESCRIPTION
**Pull request by Urigo**

### CODE REVIEW

**Comment by calebmer** [comment]
Do we need the yarn lock file? I like yarn and I generally install my dependencies with `yarn --no-lockfile`, but I feel like we need a good justification to add yarn to a project that is working fine without it 😊

**Comment by Urigo** [comment]
@calebmer I thought it might help people who use `yarn` to make sure the example will work for them.
I mean, right now everything works but maybe at some point dependencies would break something and we won't be able to immediately respond (that happens quite often on open source apps...)
Then if they want to update stuff, they can always change it and also people who would just use `npm` won't be affected.
mmmmm but I can definitely remove that

**Comment by stubailo** [comment]
> I mean, right now everything works but maybe at some point dependencies would break something and we won't be able to immediately respond (that happens quite often on open source apps...)
> Then if they want to update stuff, they can always change it and also people who would just use npm won't be affected.

The problem is that now this app will work differently for people using `yarn` and `npm`. I would say that's actually worse than it breaking for everyone.

**Comment by Urigo** [comment]
@calebmer @stubailo yes got it, probably better.
Also to strengthen your point, when I removed it there were errors because of an old dependency.
Fixed it now

**Comment by calebmer** [comment]
Tests failed for some random reason. Restarted the build.

**Comment by stubailo** [comment]
@calebmer the build is failing because optics agent has a broken peer dependency which fails on node 4.

**Comment by stubailo** [comment]
Merged in #181

**Pull request closed without merging**
