### PR TITLE
Corrected dependencies' versions

### PR DESCRIPTION
**Pull request by iurii-kyrylenko**
1. Got an error during installation:
```
npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/iurii_kyrylenko/Projects/graphql/githunt/GitHunt-API/node_modules/persistgraphql/bin/persistgraphql'
```
_Solution_: Fixed version of `persistgraphql` to the stable one (https://github.com/apollographql/persistgraphql/issues/40)

2. Got an error when migrating database:
```
Error: Cannot find module '/Users/iurii_kyrylenko/Projects/graphql/githunt/GitHunt-API/node_modules/sqlite3/lib/binding/node-v48-darwin-x64/node_sqlite3.node'
```
_Solution_: Unfixed version of `sqlite3` up from the 3.1.8 (https://github.com/mapbox/node-sqlite3/issues/749)

### CODE REVIEW

**Comment by Poincare** [comment]
Hi @iurii-kyrylenko - the issue with `persistgraphql` has been fixed with the 0.3.5 release so that change isn't needed here. I'm not sure about the `sqlite3` issue - maybe someone else can comment?

**Comment by iurii-kyrylenko** [comment]
@Poincare 
Thanks for publishing new versions to the npm.

**Comment by iurii-kyrylenko** [comment]
1. Restored caret in `persistgraphql`'s semver.
2. Also fixed lint error.

**Comment by stubailo** [comment]
Thank you!

**Pull request merged**
